In [9]:
import numpy as np
from sympy.physics.quantum.cg import CG
import tensorflow as tf
import os
import scipy.sparse as sp

In [71]:
z = np.array([[1, 2], [3, 4]])
tens = np.stack([z, np.zeros((2, 2)), np.zeros((2, 2))])
a, b, c = np.nonzero(tens)

In [72]:
abc = np.stack([a, b, c])
tens[np.nonzero(tens)]

array([1., 2., 3., 4.])

In [73]:
i, j, k = np.nonzero(tens)
ij = np.stack([i, j])
ik = np.stack([i, k])

In [74]:
print(ij[:, :10])
print(ik[:, :10])

[[0 0 0 0]
 [0 0 1 1]]
[[0 0 0 0]
 [0 1 0 1]]


In [62]:
np.ravel_multi_index(ik[:4], dims=(10, 5))

array([ 1,  2,  0,  2,  3,  4,  0,  1,  3,  4,  1,  2,  3,  4,  1,  2,  3,
        4,  5,  6,  7,  8,  9,  5,  7,  8,  5,  6,  9,  5,  6,  9,  5,  7,
        8, 10, 11, 12, 13, 10, 13, 10, 12, 14, 10, 11, 13, 14, 12, 13, 14,
       16, 17, 18, 19, 15, 17, 18, 19, 15, 16, 18, 19, 15, 16, 17, 19, 15,
       16, 17, 18, 21, 22, 23, 24, 20, 21, 22, 24, 20, 21, 20, 24, 20, 21,
       23, 25, 26, 28, 29, 25, 29, 27, 29, 25, 28, 29, 25, 26, 27, 28, 29,
       31, 32, 34, 30, 31, 32, 33, 34, 30, 31, 32, 33, 34, 31, 32, 33, 34,
       30, 31, 32, 33, 35, 37, 39, 37, 39, 35, 36, 37, 39, 39, 35, 36, 37,
       38, 39, 40, 41, 40, 42, 43, 41, 42, 43, 41, 42, 44, 43, 44, 47, 48,
       49, 47, 48, 49, 45, 46, 48, 49, 45, 46, 47, 48, 49, 45, 46, 47, 48])