In [2]:
from create_orbital_values import create_orbital_values
import numpy as np
import scipy.sparse as sp
import tensorflow as tf

In [63]:
data = np.load("../../../data/md_h2.npz", allow_pickle=True)
test_data = np.load("../../../data/md_h2_hfdensities.npz", allow_pickle=True)
data["R"] = data["R"].reshape((data["R"].shape[0] * data["R"].shape[1], 3))
N_cumsum = np.concatenate([[0], data["N"]]).cumsum()
N_rdm_cumsum = np.concatenate([[0], data["N_rdm"]]).cumsum()
data["rdm_hf"] = test_data["rdm_hf"]

In [65]:
densities = test_data["densities"]
hf_densities = test_data["hf_densities"]

In [76]:
np.absolute(densities[:, :100] - hf_densities[:, :100]).sum() / 1200

0.08881851504881051

In [38]:
tens = np.random.random((3, 16, 4))
tmp = np.einsum("abc,adc->bd", tens, tens)
tmp = tmp * (np.ones((16, 16)) - np.eye(16))
np.linalg.det(tmp)

-9015700.597832868

In [16]:
tens = np.random.random((100, 100))
for _ in range(100000):
    tens = tens * 0

In [41]:
vec = tf.constant([1, 1, 2, 2, 2, 3, 3, 3, 4, 4])
vec = tf.constant([4, 4, 3, 3, 3, 3, 2, 2, 1, 1])
am = tf.argmax(tf.cumsum(tf.cast(tf.concat([tf.constant([5]), vec[:-1]], axis=0) != vec, dtype=tf.int32)) == 3, output_type=tf.int32)
vec[tf.range(vec.shape[0]) <= am] 

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([4, 4, 3, 3, 3, 3, 2], dtype=int32)>

In [59]:
mask = tf.cast(tf.concat([tf.constant([0]), vec[:-1]], axis=0) != vec, dtype=tf.int32)
vec *

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([4, 0, 3, 0, 0, 0, 2, 0, 1, 0], dtype=int32)>

In [60]:
tf.concat([tf.constant([5]), vec[:-1]], axis=0)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([5, 4, 4, 3, 3, 3, 3, 2, 2, 1], dtype=int32)>

In [45]:
tf.argsort(tf.range(5))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>