In [1]:
import numpy as np
from sympy.physics.quantum.cg import CG
import tensorflow as tf
import os
import scipy.sparse as sp

In [3]:
tens = tf.random.uniform((10, 10, 3))
idx = tf.constant([
    [1, 2, 0],
    [3, 4, 0]
])
tf.gather_nd(tens, idx)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.8389163, 0.4745649], dtype=float32)>

In [9]:
x1 = tf.constant([1, 0, 0])
x2 = tf.gather(x1, [1, 0, 2])
x1 = tf.stack([x1, x1], axis=0)
x2 = tf.stack([x2, x2], axis=0)
tf.linalg.cross(x1, x2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 1],
       [0, 0, 1]], dtype=int32)>